services:
  - type: web
    name: desenvolva-lancamentos-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api_desenvolva_lancamentos.py
    autoDeploy: true
